'use strict';

require('dotenv').config();

const properties = {
  'forge': {
    id: 'forge',
    name: 'Le Nido — Forge',
    type: 'Studio',
    location: 'Lekki Phase 1, Lagos',
    tagline: 'Your private retreat in the heart of Lekki',
    description:
      'A beautifully designed studio apartment in Lekki Phase 1. Fully air-conditioned, high-speed WiFi, Netflix-ready smart TV, and a fully equipped kitchenette. Perfect for solo travelers, business professionals, and couples looking for a quiet, stylish base in Lagos.',
    maxGuests: 2,
    bedrooms: 0,
    bathrooms: 1,
    amenities: [
      'High-Speed WiFi',
      'Air Conditioning',
      'Smart TV / Netflix',
      'Fully Equipped Kitchenette',
      '24/7 Security',
      'Dedicated Parking',
      'Backup Generator',
      'Water Dispenser',
      'Iron & Ironing Board',
      'Premium Toiletries',
      'Clean Linens & Towels',
      'Workspace Desk',
    ],
    pricing: {
      night: 85000,
      week: 530000,
      month: 1800000,
    },
    images: [
      '/assets/properties/Forge/Studio_2.jpg',
      '/assets/properties/Forge/Studio_5.jpg',
      '/assets/properties/Forge/Studio_6.jpg',
      '/assets/properties/Forge/Studio_9.jpg',
      '/assets/properties/Forge/Studio_10.jpg',
      '/assets/properties/Forge/Studio_11.jpg',
      '/assets/properties/Forge/Studio_12.jpg',
      '/assets/properties/Forge/Studio_13.jpg',
      '/assets/properties/Forge/Studio_14.jpg',
      '/assets/properties/Forge/Studio_15.jpg',
      '/assets/properties/Forge/Studio_16.jpg',
      '/assets/properties/Forge/Studio_17.jpg',
      '/assets/properties/Forge/Studio_18.jpg',
      '/assets/properties/Forge/Studio_19.jpg',
      '/assets/properties/Forge/Studio_20.jpg',
    ],
    icalUrl: process.env.ICAL_URL_FORGE || '',
  },

  'cedar': {
    id: 'cedar',
    name: 'Le Nido — Cedar',
    type: '1 Bedroom',
    location: 'Lekki Phase 1, Lagos',
    tagline: 'Spacious comfort with a Lagos state of mind',
    description:
      'A premium 1-bedroom apartment with a separate living area in Lekki Phase 1. Ideal for business travelers, small families, or anyone who wants extra space and privacy. Features a dedicated bedroom with ensuite, open-plan living room, and a full kitchen.',
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      'High-Speed WiFi',
      'Air Conditioning (All Rooms)',
      'Smart TV / Netflix',
      'Fully Equipped Kitchen',
      'Dining Area',
      '24/7 Security',
      'Dedicated Parking',
      'Backup Generator',
      'Washing Machine',
      'Water Dispenser',
      'Iron & Ironing Board',
      'Premium Toiletries',
      'Clean Linens & Towels',
      'Workspace Desk',
    ],
    pricing: {
      night: 120000,
      week: 750000,
      month: 2500000,
    },
    images: [
      '/assets/properties/Cedar/Image_1.jpg',
      '/assets/properties/Cedar/Image_2.jpg',
      '/assets/properties/Cedar/Image_3.jpg',
      '/assets/properties/Cedar/Image_4.jpg',
      '/assets/properties/Cedar/Image_5.jpg',
      '/assets/properties/Cedar/Image_6.jpg',
      '/assets/properties/Cedar/Image_7.jpg',
      '/assets/properties/Cedar/Image_8.jpg',
      '/assets/properties/Cedar/Image_9.jpg',
      '/assets/properties/Cedar/Image_10.jpg',
      '/assets/properties/Cedar/Image_11.jpg',
      '/assets/properties/Cedar/Image_12.jpg',
      '/assets/properties/Cedar/Image_13.jpg',
      '/assets/properties/Cedar/Image_14.jpg',
      '/assets/properties/Cedar/Image_15.jpg',
      '/assets/properties/Cedar/Image_16.jpg',
    ],
    icalUrl: process.env.ICAL_URL_CEDAR || '',
  },
};

module.exports = properties;
